# Generated by Django 3.1.7 on 2021-04-02 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('canvas_id', models.IntegerField()),
                ('corrector', models.CharField(max_length=50)),
                ('ensayos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_review.ensayo')),
            ],
        ),
    ]
