# Generated by Django 3.1.7 on 2021-04-08 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0002_alumne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arte',
            name='fecha_entrega',
        ),
    ]
