# Generated by Django 3.1.7 on 2021-04-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0004_alumne_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumne',
            name='corrector',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
