# Generated by Django 3.1.7 on 2021-04-19 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0005_auto_20210419_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumne',
            name='ensayos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peer_review.ensayo'),
        ),
    ]
