# Generated by Django 3.1.7 on 2021-04-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0008_auto_20210425_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensayoalumnerelation',
            name='corregido_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ensayoalumnerelation',
            name='corregido_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
